accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('delete/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('password/', views.change_password, name='change_password'),
    path('', views.index, name="index"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("",include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update', views.update, name="update"),
    path('<int:pk>/delete', views.delete, name="delete"),
    path('<int:pk>/detail/create', views.comments_create, name='comments_create'),
    path('<int:review_pk>/detail/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('search/',views.search, name="search"),
    path('searchfail/',views.searchfail, name="searchfail"),
]

reviews/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

class Review(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    like_users = models.ManyToManyField(get_user_model(), related_name='like_articles')
    title = models.CharField(max_length=10)
    content = models.TextField()
    grade = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Review, on_delete=models.CASCADE)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    content = models.CharField(max_length=200, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.content

reviews/forms.py
from ftplib import error_perm
from django import forms
from .models import Review,Comment

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['title', 'content','grade']
        labels = {
            "title": "제목",
            "content": "내용",
            "grade":"평점",
        }
class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields=['content',]
        labels = {
            "content": "",
        }
        error_messages = {
            'content': {
                'required':"",
            },
        }

reviews/views.py
from django.shortcuts import render,redirect,get_object_or_404
from .models import Review,Comment
from .forms import ReviewForm,CommentForm
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.core.paginator import Paginator
from django.contrib.auth import get_user_model
from accounts.models import User

def index(request):
    reviews = Review.objects.all().order_by('-pk')
    page = int(request.GET.get('p', 1))
    pagenator = Paginator(reviews, 5)
    boards = pagenator.get_page(page)
    context = {
        'reviews': reviews,
        "boards":boards,
    }
    return render(request, 'reviews/index.html', context)
    
@login_required
def create(request):
    if request.method == 'POST':
        Review_Form = ReviewForm(request.POST)
        if Review_Form.is_valid():
            post = Review_Form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('reviews:index')
    else: 
        Review_Form = ReviewForm()
    context = {
        'Review_Form': Review_Form
    }
    return render(request, 'reviews/new.html', context=context)

@login_required()
def detail(request, pk):
    review = Review.objects.get(pk=pk)
    review = get_object_or_404(Review, pk=pk)
    comments = Comment.objects.filter(article_id=pk)
    comment_form = CommentForm(request.POST)
    context = {
            "review": review,
            "all": review.like_users.all(),
            "count": review.like_users.count,
            "comment_form":comment_form,
            "comments":comments,
    }
    return render(request, "reviews/detail.html", context)
    
@login_required
def update(request, pk):
    reviews = Review.objects.get(pk=pk)
    if request.method == "POST":
        Review_form = ReviewForm(request.POST, instance=reviews)
        if Review_form.is_valid():
            Review_form.save()
            return redirect("reviews:index")
    else:
        Review_form = ReviewForm(instance=reviews)
    context = {
        "Review_form": Review_form,
        "reviews": reviews,
    }
    return render(request, 'reviews/update.html', context)
    
@login_required
def delete(request, pk):
    reviews = Review.objects.get(pk=pk)
    reviews.delete()
    return redirect('reviews:index')
@login_required()
def like(request, pk):
    reviews = get_object_or_404(Review, pk=pk)
    if reviews.like_users.filter(id=request.user.pk).exists():
        reviews.like_users.remove(request.user)
    else:
        reviews.like_users.add(request.user)
    return redirect('reviews:detail', pk)

@require_POST
def comments_create(request, pk):
    if request.user.is_authenticated:
        reviews = get_object_or_404(Review, pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.article = reviews
            comment.user = request.user
            comment.save()
        return redirect('reviews:detail', reviews.pk)
    return redirect('accounts:login')


@require_POST
def comments_delete(request, review_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)  
        if request.user == comment.user:
            comment.delete()
    return redirect('reviews:detail', review_pk)


def search(request):
    search = request.GET.get('search','')
    c = Comment.objects.filter(content = search)

    list_ =[]
    for i in c:
        r = Review.objects.get(pk=i.article_id).id
        list_.append(r)

    search_list = Review.objects.filter(
            Q(title__icontains = search) | #제목
            Q(content__icontains = search)| #내용
            Q(grade__icontains = search)| #평점
            Q(user_id__username__icontains = search)| #작성자 이름
            Q(id__in=list_) #댓글
        )

    if search:
        if search_list:
            page = int(request.GET.get('p', 1))
            pagenator = Paginator(search_list, 3)
            boards = pagenator.get_page(page)
            return render(request, 'reviews/search.html',{'search':search, "boards":boards, "search_list":search_list})
        else:
            k="검색 결과가 없습니다 다시 검색해주세요"
            context = {
                "v":k
                }
            return render(request,'reviews/searchfail.html', context)
    else:
        k="검색 결과가 없습니다 다시 검색해주세요"
        context = {
            "v":k
        }
        return render(request,'reviews/searchfail.html', context)
def searchfail(request):
    return render(request,'reviews/searchfail.html')

reviews/templates/reviews/detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}

  <div class="container" style="width: 600px">
    <div class="my-5">
      <h3 class="fw-lighter text-center">notice</h3>
    </div>

    <div class="p-4" style="box-shadow: 4px 12px 30px 6px rgb(0 0 0 / 9%); border-radius: 15px">
      {% if review.user == request.user %}
        <div class="d-flex justify-content-end">
          <a class="mx-2" href="{% url 'reviews:update' review.pk%}" style="color: #35C5F0">수정</a>
          <a class="mx-1" href="{% url 'reviews:delete' review.pk %}" style="color: #f77">삭제</a>
        </div>
      {% endif %}
      <div class="">
        <h2 class="fw-bold my-3">{{ review.title }}</h2>
        <p class="text-muted m-0">{{ review.user }}
          <span class="fw-lighter">
            |
            {{ review.created_at }}</span></p>
      </div>
      <hr>
      <div class="mt-4">
        <p class="fs-4 p-1" style="height:100%">{{ review.content }}</p>
      </div>
      <div class="d-flex flex-column justify-content-center align-items-center">
        <form action="{% url 'reviews:like' review.pk %}" method='POST' class="mt-4">
          {% csrf_token %}
          {% if user in all %}
            <button class="btn btn-link text-danger p-0">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewbox="0 0 16 16">
                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
              </svg>
            </button>
          {% else %}
            <button class="btn btn-link text-danger p-0">
              <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewbox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
              </svg>
            </button>
          {% endif %}
        </form>
        <p class="mb-0">{{ count }}</p>
      </div>
      <hr>

      <!--read-->
      {% if comments %}
        <p>
          <b>{{ comments|length }}개의 댓글이 있습니다.</b>
        </p>
      {% endif %}
      <ul class="ps-2">
        {% for comment in comments %}
          <li>
            {{ comment.user }}
            -
            {{ comment.content }}
            <!--delete-->
            {% if user == comment.user %}
              <form action="{% url 'reviews:comments_delete' review.pk comment.pk %}" method="POST" class="d-inline">
                {% csrf_token %}
                <input type="submit" value="삭제" class="btn btn-outline-danger ms-2">
              </form>
            {% endif %}
          </li>
          {% empty %}
          <p>댓글이 없어요..</p>
        {% endfor %}
      </ul>

      <!--create-->
      <div>
        {% if request.user.is_authenticated %}
          <form action="{% url 'reviews:comments_create' review.pk %}" method="POST">
            {% csrf_token %}
            <div class="d-flex w-100">
              <div class="w-100">{% bootstrap_form comment_form %}</div>
              <div class="ms-3"><input type="submit" value="댓글 작성" class="btn btn-outline-dark"></div>
            </div>
          </form>
        {% else %}
          <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
        {% endif %}
      </div>
    </div>
  </div>
  {% endblock%}

reviews/templates/reviews/index.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container">
    <h1 class="text-center mt-5 ">게시판</h1>
    <div class="row mt-2">
      <div class="col-12">
        <div class="row mt-5">
          <div class="col-12">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">평점</th>
                  <th scope="col">제목</th>
                  <th scope="col">작성자</th>
                  <th scope="col">작성일</th>
                </tr>
              </thead>
              <tbody class="table-group-divider">
                {% for board in boards %}
                  <tr>
                    {% if board.grade == 1 %}
                      <th scope="row">⭐️</th>
                    {% elif board.grade == 2 %}
                      <th scope="row">⭐️⭐️</th>
                    {% elif board.grade == 3 %}
                      <th scope="row">⭐️⭐️⭐️</th>
                    {% elif board.grade == 4 %}
                      <th scope="row">⭐️⭐️⭐️⭐️</th>
                    {% elif board.grade == 5 %}
                      <th scope="row">⭐️⭐️⭐️⭐️⭐️</th>
                    {% endif %}
                    <td>
                      <a class="text-dark fw-bolder" href="{% url 'reviews:detail' board.pk %}">{{board.title}}</a>
                    </td>
                    <td>{{board.user}}</td>
                    <td>{{board.created_at |date:'m월 d일'}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col-12">
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                {% if boards.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?p={{ boards.previous_page_number }}">이전</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#">이전</a>
                  </li>
                {% endif %}
                <li class="page-item">
                  <a class="page-link" href="#">{{ boards.number }}
                    /
                    {{ boards.paginator.num_pages }}</a>
                </li>
                {% if boards.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?p={{ boards.next_page_number }}">다음</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#">다음</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reviews/templates/reviews/new.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center">글쓰기</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form Review_Form %}
        <button type="submit" class="btn btn-dark">제출</button>
      </form>
    </div>
  </div>
{% endblock %}

reviews/templates/reviews/search.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container">
    <h1 class="text-center mt-5 ">게시판</h1>
    <div class="row mt-2">
      <div class="col-12">
        <div class="row mt-5">
          <div class="col-12">
            <table class="table">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">평점</th>
                  <th scope="col">제목</th>
                  <th scope="col">작성자</th>
                  <th scope="col">작성일</th>
                </tr>
              </thead>
              <tbody class="table-group-divider">
                {% for board in boards %}
                  <tr>
                    {% if board.grade == 1 %}
                      <th scope="row">⭐️</th>
                    {% elif board.grade == 2 %}
                      <th scope="row">⭐️⭐️</th>
                    {% elif board.grade == 3 %}
                      <th scope="row">⭐️⭐️⭐️</th>
                    {% elif board.grade == 4 %}
                      <th scope="row">⭐️⭐️⭐️⭐️</th>
                    {% elif board.grade == 5 %}
                      <th scope="row">⭐️⭐️⭐️⭐️⭐️</th>
                    {% endif %}
                    <td>
                      <a class="text-dark fw-bolder" href="{% url 'reviews:detail' board.pk %}">{{board.title}}</a>
                    </td>
                    <td>{{board.user}}</td>
                    <td>{{board.created_at |date:'m월 d일'}}</td>
                  </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
        <div class="row mt-2">
          <div class="col-12 my-5">
            <nav aria-label="Page navigation example">
              <ul class="pagination justify-content-center">
                {% if boards.has_previous %}
                  <li class="page-item">
                    <a class="page-link" href="?p={{ boards.previous_page_number }}">이전</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#">이전</a>
                  </li>
                {% endif %}
                <li class="page-item">
                  <a class="page-link" href="#">{{ boards.number }}
                    /
                    {{ boards.paginator.num_pages }}</a>
                </li>
                {% if boards.has_next %}
                  <li class="page-item">
                    <a class="page-link" href="?p={{ boards.next_page_number }}">다음</a>
                  </li>
                {% else %}
                  <li class="page-item disabled">
                    <a class="page-link" href="#">다음</a>
                  </li>
                {% endif %}
              </ul>
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

reviews/templates/reviews/searchfail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container d-flex justify-content-center">
    <h1>{{v}}</h1>
  </div>
{% endblock %}

reviews/templates/reviews/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center">글수정</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form Review_form %}
        <input type="submit" value="수정" class="btn btn-dark">
        <a href="{% url 'reviews:detail' reviews.pk %}" class="btn btn-light">취소</a>
      </form>
    </div>
  </div>
{% endblock %}