accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('delete/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('password/', views.change_password, name='change_password'),
    path('', views.index, name="index"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("",include("reviews.urls")),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
# from .models import User

from django.contrib.auth import get_user_model

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'email')

class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ('first_name', 'last_name', 'email')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from .forms import CustomUserChangeForm, CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.

def index(request):
    all = get_user_model().objects.all()
    context = {
        'v':all,
    }
    return render(request,"accounts/index.html",context)
def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('reviews:index')
    else:   
        form = CustomUserCreationForm()

    context = {
        'form' : form,
    }

    return render(request, 'accounts/signup.html', context)

@login_required
def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('accounts:detail', request.user.pk)
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form
    }
    return render(request, 'accounts/update.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('reviews:index')

def detail(request, pk):
    user = get_user_model().objects.get(pk=pk)
    context = {
        'user': user
    }
    return render(request, 'accounts/detail.html', context)

def login(request):
    if request.method == 'POST':
        # AuthenticationForm은 ModelForm이 아님!
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            # 세션에 저장
            # login 함수는 request, user 객체를 인자로 받음 
            # user 객체는 어디있어요? 바로 form에서 인증된 유저 정보를 받을 수 있음
            auth_login(request, form.get_user())
            # http://127.0.0.1:8000/accounts/login/?next=/articles/1/update/
            # request.GET.get('next') : /articles/1/update/
            return redirect(request.GET.get('next') or 'reviews:index')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect("accounts:index")

@login_required
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('reviews:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {
    'form': form,
    }
    return render(request, 'accounts/change_password.html', context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center my-5">비밀번호 변경</h1>
      <form action="{% url 'accounts:change_password' %}" method="POST">
        {% csrf_token %}
        {% bootstrap_form form%}
        <button type="submit" class="btn btn-dark mt-3">제출</button>
      </form>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="my-5 text-center">{{ user.username }}님의 프로필</h1>
      <hr>
      <div class="d-flex">
        <p class="mb-0" style="width:50%;">이메일</p>
        <p class="mb-0" style="width:50%;">{{ user.email }}</p>
      </div>
      <hr>
      <div class="d-flex">
        <p class="mb-0" style="width:50%;">가입 시각</p>
        <p class="mb-0" style="width:50%;">{{ user.date_joined }}</p>
      </div>
      <hr>
      {% if request.user == user %}
        <div class="d-flex justify-content-end">
          <a href="{% url 'accounts:update' %}" class="btn btn-primary mt-3 me-3">회원정보수정</a>
          <a href="{% url 'accounts:delete' %}" class="btn btn-danger mt-3">회원탈퇴</a>
        </div>
      {% endif %}
    </div>
  </div>
  {% endblock%}

accounts/templates/accounts/index.html
{% extends 'base.html' %}
{% block content %}
  <h1 class="text-center my-5 ">회원 목록</h1>
  <div class='container'>
    <table class='table'>
      <thead>
        <tr>
          <th scope='col'>회원 번호</th>
          <th scope='col'>회원 이름</th>
          <th scope='col'>이메일</th>
          <th scope='col'>가입일</th>
        </tr>
      </thead>
      <tbody>
        {% for member in v %}
          <tr>
            <th scope='row'>{{ member.id }}</th>
            <td>
              <a href='{% url 'accounts:detail' member.pk %}' class="text-decoration-none text-dark fw-bold">{{ member.username }}</a>
            </td>
            <td>{{ member.email }}</td>
            <td>{{ member.date_joined }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container" style="width: 600px">
  <div class="my-5">
    <h1>로그인</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-dark">제출</button>
    </form>
  </div>
</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
<div class="container" style="width: 600px">
  <div class="my-5">
    <h1>회원가입</h1>
    <form action="" method="POST">
      {% csrf_token %}
      {% bootstrap_form form %}
      <button type="submit" class="btn btn-dark">제출</button>
    </form>
  </div>
</div>

{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block content %}
  <div class="container" style="width: 600px">
    <div class="my-5">
      <h1 class="text-center my-5">회원 정보 수정</h1>
      <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <a href="{% url 'accounts:change_password' %}" class="btn btn-outline-dark me-3">비밀번호 수정하러 가기</a>
        <button type="submit" class="btn btn-dark">제출</button>
      </form>
    </div>
  </div>
{% endblock content %}