accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('delete/', views.delete, name='delete'),
    path('signup/', views.signup, name='signup'),
    path('update/', views.update, name='update'),
    path('<int:pk>/detail', views.detail, name='detail'),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path('password/', views.change_password, name='change_password'),
    path('', views.index, name="index"),
]

pjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include("accounts.urls")),
    path("",include("reviews.urls")),
]

reviews/urls.py
from django.urls import path
from . import views

app_name = 'reviews'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('<int:pk>/update', views.update, name="update"),
    path('<int:pk>/delete', views.delete, name="delete"),
    path('<int:pk>/detail/create', views.comments_create, name='comments_create'),
    path('<int:review_pk>/detail/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('search/',views.search, name="search"),
    path('searchfail/',views.searchfail, name="searchfail"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com"/>
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="crossorigin"/>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap" rel="stylesheet"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.0/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>

    <style>
      * {
        font-family: "Noto Sans KR", sans-serif;
      }

      ul {
        list-style: none;
      }
    </style>
    <title>HOME</title>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-light px-5">
      <div class="container-fluid ">
        <a class="navbar-brand me-5 fs-4 fw-bold" href="{% url 'reviews:index' %}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href={% url 'accounts:index' %}>회원 목록</a>
            </li>
            {% if user.is_anonymous %}
              <li class="nav-item">
                <a class="nav-link active" href={% url 'accounts:signup' %}>회원가입</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" href={% url 'accounts:login' %}>로그인</a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link mx-3 active" href="{% url 'reviews:create' %}">글 쓰기</a>
              </li>
            {% endif %}
          </ul>
          {% if not user.is_anonymous %}
            <a class="nav-link mx-3" href={% url 'accounts:logout' %}>
              <strong>{{user}}</strong>님 로그아웃</a>
          {% endif %}
          <form class="d-flex" action="{% url 'reviews:search' %}">
            <input class="form-control me-2" type="search" placeholder="댓글,작성자,제목,내용,평점으로 검색하세요" name="search" aria-label="Search">
            <button class="btn btn-outline-success me-2" type="submit">
              Search
            </button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %}{% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.min.js" integrity="sha384-7VPbUDkoPSGFnVtYi0QogXtr74QeVeeIs99Qfg5YCF+TidwNdjvaKZX19NZ/e6oz" crossorigin="anonymous"></script>
  </body>

</html>